### ISSUE TITLE
More fine-grained SiteDB Roles for accessing protected APIs

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/DBS#209]
**Original TRAC ticket 4235 reported by giffels**
I think that it makes sense to have more fine-grained SiteDB Roles to access protected APIs. People from the transfer and workflow team do only need access to the update DS and Files APIs for invalidating DSs. They do not need to have access to the insert APIs for example. So we can follow the principle of least privilege here. 

Cheers,
Manuel

**Comment by yuyiguo** [comment]
No longer needed.
