### ISSUE TITLE
add unittests for files API with detail=True

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/DBS#239]
**Original TRAC ticket 4272 reported by yuyi**
Valentin reported an bug in Oct 2013 release testing. see below for the reported bug:

curl -k --key ~/.globus/userkey.pem --cert ~/.globus/usercert.pem "https://cmsweb-testbed.cern.ch/dbs/prod/global/DBSReader/files/?block_name=/SingleMu/Run2011B-WMu-19Nov2011-v1/RAW-RECO%2319110c74-1b66-11e1-a98b-003048f02c8a&run_num=177487&detail=True"
{'exception': 500, 'type': 'HTTPError', 'message': 'dbsException due to internal server error: '}

I checked DBS3 unit tests and did not see we are testing files API with detail=true. We need to add these unit tests in both client and server to avoid future errors in our release.

**Comment by yuyiguo** [comment]
Done.
