### ISSUE TITLE
DBS3 API transient error while using dataset regex

### ISSUE THREAD

**Issue by merictaze** [dmwm/DBS#400]
I've encountered a transient problem in DBS, I don't have much details, but if you want to check the logs, here is the details:

I've got VALID Fall11 samples from DBS on July 11, and it returned only 203 datasets.
I used both DBS python API, and DBS web-page. You can find dataset returned by DBS at:
/afs/cern.ch/user/m/mtaze/work/public/dbs3/Fall11.txt

Since PhEDEx has ~13k Fall11 samples in TMDB, I checked DBS again on July 14, and this time it returned ~13k valid datasets.

I also checked the history in case I had given wrong dataset regex, but it was the same,
/*/*Fall11*/*

Regards,
Meric

**Comment by yuyiguo** [comment]
It was because DBS API only show valid dataset by default, if the dataset is in PRODUCTION, it will not show in default searching until the dataOps change the status to VALID.
