### ISSUE TITLE
filelumis to accept list in logical_file_name field

### ISSUE THREAD

**Issue by AdrianAlan** [dmwm/DBS#428]
Hi

Would it be possible to change the DBSReader filelumis interface, so it accepts an array of files as a parameter (create similar POST)? Or equivalently include filelumis object under the files interface with details flag set to True (even better)?

The use case is simmilar to issue #280 i.e. construct subset of lumis which number of events is close to desired value. We are constructing subset based on num_events per files (approximation is good enough), but then we have to describe the subset with lumis.

Right now it's two step:
1 get files per dataset (1 query);
2 get lumi_section_num by filelumis with logical_file_name of desired file as parameter (num_files queires).

One of those solutions will help us to reduce the delay (along with number of queries from 1+num_files to 2) we are getting while processing for big datasets (e.g. 250M events). 

Best regards,
Adrian Alan Pol

**Comment by yuyiguo** [comment]
@AdrianAlan 
New API listFileLumiArray is added to address this request.

**Comment by AdrianAlan** [comment]
@yuyiguo  Thanks a million. Is that in prod?

**Comment by yuyiguo** [comment]
@AdrianAlan Yes.

**Comment by AdrianAlan** [comment]
@yuyiguo Hi again, can you give an example request? I can't find any documentation under https://cmsweb.cern.ch/dbs/prod/global/DBSReader/

**Comment by yuyiguo** [comment]
Sorry for the confusing. The server side API is called filelumis, just like the old filelums API. But this one is called with POST so it can accept a list of long flns. It is one document. You will find it under POST call.

I had bug in the prod so it fails depending on how you call the API. I have fixed on my testbed and will have on prod in March CMSWEB release. Just give you an example, here is a simple call, but you may add run_num and so too.

curl -X POST -H "Content-type: application/json" -ki --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem "https://dbs3-test1.cern.ch/dbs/dev/global/DBSReader/filelumis" -d '{"logical_file_name":["/store/mc/Fall08/BBJets250to500-madgraph/GEN-SIM-RAW/IDEAL_/18458/0.root", "/store/mc/Fall08/BBJets250to500-madgraph/GEN-SIM-RAW/IDEAL_/34661/0.root"], "validFileOnly":0}'

**Comment by yuyiguo** [comment]
listFileLimiArray is the API called in DBSClient. It is not in prod, but available on VM. Will be on prod on March release.

**Comment by yuyiguo** [comment]
Done in DBS 3.2.9.
