### ISSUE TITLE
need an API to find out dataset name by providing dataset id

### ISSUE THREAD

**Issue by vkuznet** [dmwm/DBS#434]
Many DBS APIs return dataset_id (I think it is database ID assigned to dataset). I'm using this IDs in new mining project and need to do a reverse look-up. By knowing dataset_id I need to find out dataset name. Could you please implement this.

**Comment by yuyiguo** [comment]
Added dataset_id search for both GET and POST calls. 
Remeber to add unit tests.

**Comment by vkuznet** [comment]
Yuyi,
do you have a server to test this functionality?
Thanks,
Valentin.

**Comment by yuyiguo** [comment]
Not yet, Valentin. I’ll let you know when I have it. Working on the DBS issues for Feb release. I am done with this API, but haven’t built a test bed yet.
Yuyi

**Comment by yuyiguo** [comment]
Done, in HG0215 release.
