### ISSUE TITLE
using dbsClient for own publication script

### ISSUE THREAD

**Issue by matt-komm** [dmwm/DBS#439]
Hello,

I like to use the dbsClient to publish some files which crab is unable to do so (crab-dev cannot help). I tried to follow the instructions in dbsClient.py but to me it seems as if they are either outdated or not working properly. Can you provide me with some minimal instructions of how to use the interface to get a file published under a name that I can choose?
So far, I tried to follow how crab is using it [1] and just modied the 'dataset' dictonary to another processed_ds_name. This resulted strangely in an error "duplicated lfn". 

I started again using just the 'insertFiles' method with the minimal settings as stated in the dbsClient.py file (here is my request [2]). This results in an "internal server error". The primary dataset and the dataset are already in dbs. Do I explicitly need to create a block or something else (e.g. acquisition_era) first?

What am I doing wrong? What would be the easiest way of publishing a file using dbsClient.py? Are the instruction in the file up-to-date?

Beyond that, it might be good to get a better error description from the server.

I am at CERN, so meeting in person would be great...
Best regards,
Matthias

[1] https://github.com/dmwm/CRAB2/blob/master/python/crab_dbs3publish.py#L418

[2] 
[{'check_sum': '4108645093', 'event_count': '61087', 'logical_file_name': '/store/user/mkomm/SingleMu/2014Nov17_stpol/0b660941bfe423b9433b072f93b65912/output_Skim_9_1_K3w.root', 'block': '/SingleMu/mkomm-2014Nov17_stpol_foo-0b660941bfe423b9433b072f93b65912/USER#842def0f-bfdd-4b25-8465-f8d3361900c0', 'dataset': '/SingleMu/mkomm-2014Nov17_stpol_foo-0b660941bfe423b9433b072f93b65912/USER'}]

**Comment by yuyiguo** [comment]
@matt-komm 
@belforte 
@ericvaandering 
You may find DBS client document at https://cms-http-group.web.cern.ch/cms-http-group/apidoc/dbs3-client/current/dbs.apis.html. If you find a particular API document is wrong, please let us know and we will update it.

Publishing data in DBS requires a lot of details to be taken care. What you did by taking crab3 as example is a right approach.   We don't suggest DBS clients to call individual API to in server a file. The best way to do is call  insertBulkBlock API to insert a completed block.

The error you got was expected, for example the "duplicated lfn". Lfns have to be unique across entire CMS data. If you only modified the dataset and try to insert the rest of data as they were, you would get this kind errors.

**Comment by matt-komm** [comment]
Thanks for your answer. So I tried to invalidate first the already partially and wrongly published files before publishing the same lfns under a new dataset name ... unfortunately, I still get an "duplicated lfn" error although the dbs query "dataset file=<one of my file's lfn>" returns empty now after invalidating. Can I not publish those files again even when their original dataset is invalidated?

**Comment by yuyiguo** [comment]
Invalidate anything in DBS means marking it invalid and will not physically remove it from DBS. So the Lfns are still in DBS. So you cannot reuse them.

**Comment by matt-komm** [comment]
Well that is very very bad for me... Is there a particular reason for this design choice. Basically, users will have to rerun their jobs when just something with the publication did not work out (e.g. config mistake). Like in my case, crab by default prevents from publishing the outputs of two tasks under the same name because it misses proper checks for lumi overlaps (according to dev).

**Comment by belforte** [comment]
Matthias, we need to go back to your issue, make sure it is well understood and
then find the proper solution in crab context, even modifying Crab3 if needed.
Although if you change configuration the only good solution is a new
dataset.
In the end we will always prefer robust bookkeeping to convenience,
replacing a file with another with same name is too fragile.

On 01/20/2015 10:41 PM, Matthias Komm wrote:
> Well that is very very bad for me... Is there a particular reason for this design choice. Basically,
> users will have to rerun their jobs when just something with the publication did not work out (e.g.
> config mistake). Like in my case, crab by default prevents from publishing the outputs of two tasks
> under the same name because it misses proper checks for lumi overlaps (according to dev).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/DBS/issues/439#issuecomment-70739619>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by matt-komm** [comment]
Ok after learning and reviewing all the information about crab & dbs I found a working solution suddenly. I just set the block publication size to 1 and skipped the check if some files where already published before under the original dataset name. This way, publication will fail only for those files already present in dbs but all missing files are getting published.
