### ISSUE TITLE
add valid flag on dbs api.

### ISSUE THREAD

**Issue by ticoann** [dmwm/DBS#445]
Following is the method in dbs client which need to have validOnly flag. Yuyi told me the last 2 is already has. So listFiles is the only one which needed this flag. 

1. Flag should be independent of other parameters especially 'detail ' - regard less detail option it should return the correct result.
2. File should be invalid if dataset is invalid (so returns nothing if dataset is invalid)
3. REST api need to have the same behavior as dbsClient behavior.

listFiles
listFileLumis
listFileSummaries

**Comment by yuyiguo** [comment]
To have all the ValidFileOnly flag returns the same set of results, we have to update the other APIs that  use this flag to check if the dataset is valid or not. Current implementation only checks is_file_valid of files table.

**Comment by ticoann** [comment]
Sure, as you said, it has to be consistent.

**Comment by yuyiguo** [comment]
Interesting. The sql was originally only pick valid files, but it was commented out and changed to pick all the files. It did not say what triggered the changed.

**Comment by ericvaandering** [comment]
Can you track to when? Before/after the github migration?

**Comment by ticoann** [comment]
> Interesting. The sql was originally only pick valid files, but it was commented out and changed to pick all the files. It did not say what triggered the changed.

When did this happen? Maybe DBS2 was that way before. For me, default value returning only valid files makes more sense.

**Comment by yuyiguo** [comment]
The change happened more than 4 years ago. The dao started without checking is_file_valid column so it had all files.
  
Then it required is_file_valid=1
https://svnweb.cern.ch/trac/CMSDMWM/browser/DBS/trunk/Server/Python/src/dbs/dao/Oracle/File/List.py?rev=9873


Later, it changed to all files
https://svnweb.cern.ch/trac/CMSDMWM/browser/DBS/trunk/Server/Python/src/dbs/dao/Oracle/File/List.py?rev=9974


So this is not a new thing. It has been return all files more than 4 years. 

Seangchan, I cannot change the behavior of DBS API to return valid file by default as I mentioned before. the thing I can do is what we discussed in this issue.

**Comment by ticoann** [comment]
> Seangchan, I cannot change the behavior of DBS API to return valid file by default as I mentioned before. the thing I can do is what we discussed in this issue.

Sure, I just meant the other way make more sense. :smile:

**Comment by yuyiguo** [comment]
@ticoann 
I have have update dbs vm with validFileOnly flag for listFiles api under both detail=0/1.
https://dbs3-test1.cern.ch/dbs/dev/global/DBSReader/
Please take a look and let me know if this works for you or not.

**Comment by ticoann** [comment]
Thanks Yuyi, I guess it is not yet in master branch.
https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L839
Let me know when it gets updated.

**Comment by yuyiguo** [comment]
Works to be done on daos of listFileLumis and listFileSummeris to check dataset access type is VALID or PRODUCTION.

**Comment by yuyiguo** [comment]
Done as discussed in DBS 3.2.9.
