### ISSUE TITLE
api to get the parent file with detail info

### ISSUE THREAD

**Issue by ticoann** [dmwm/DBS#455]
WMAgent has a use case to process files with parent.

Idealy this function could return detailed file information if the detail flag is set.
https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L844

currently is just returning lfns

**Comment by yuyiguo** [comment]
Detailed file info is supposed to get from listFile call instead of parentage call that will give a list of parents. We cannot combined the two APIs into one.

**Comment by ticoann** [comment]
In that case, lf listFiles takes multiple lfns as parameter that will be fine.

**Comment by yuyiguo** [comment]
Got you. I am closing this one.
