### ISSUE TITLE
listFileLumis dbs client function need to support multiple lfns as input.

### ISSUE THREAD

**Issue by ticoann** [dmwm/DBS#456]
There is a case we need to get the run lumi information from parent files of files in a block.
Those parent files might not be  in the same block, currently we have to make this call for each lfn which it not very efficient.

**Comment by yuyiguo** [comment]
@ticoann 
Is this what you wanted? We also have a client API with this server REST API.
https://github.com/yuyiguo/DBS/blob/CMSWEB-HG1503a-Test/Server/Python/src/dbs/web/DBSReaderModel.py#L1053

**Comment by yuyiguo** [comment]
@ticoann 
Do you need the listFile API to accept a list of LFN too?

**Comment by ticoann** [comment]
Yes, please.

**Comment by yuyiguo** [comment]
I am working on the listFile API to accept a list of LFN for both detail=1/0.

**Comment by yuyiguo** [comment]
API listFileLumiArray and listFileArray was created in DBS 3.2.9.
