### ISSUE TITLE
Submit migration API says dataset already in destination while listDatasets return empty list

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/DBS#459]
Here is the code to reproduce the issue:

import dbs.apis.dbsClient as dbsClient
import os

proxy = os.environ.get("SOCKS5_PROXY")
migrateURL="https://cmsweb.cern.ch/dbs/prod/phys03/DBSMigrate"
migrateApi = dbsClient.DbsApi(url=migrateURL, proxy=proxy)

destReadApi = dbsClient.DbsApi(url="https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader", proxy=proxy)
data = {'migration_input': '/glugluToX2000ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT/sdas-glugluToX2000ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633/USER', 'migration_url': 'https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader'}

try:
    migrateApi.submitMigration(data)
except Exception, ex:
    print ex

print destReadApi.listDatasets(dataset='/glugluToX2000ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT/sdas-glugluToX2000ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633/USER', detail=True)

**Comment by yuyiguo** [comment]
I am confused that which one is you source for migration. The destination and source url are the same in the code?

**Comment by HassenRiahi** [comment]
I am calling the submitMigrate API only to confirm the existence of the dataset in phys03. But the issue is why the listDataset return empty list when submitMigrate confirms that the dataset is in phys03?

**Comment by yuyiguo** [comment]
Here is what I used  on my web browser directly: (Note: datasets API only return valid dataset. This dataset is invalid. To get it, you may use dataset_access_type=* or INVALID)

https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader/datasets?detail=1&dataset_access_type=*&dataset=/glugluToX2000ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT/sdas-glugluToX2000ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633/USER


This is what I got:
[{u'primary_ds_name': 'glugluToX2000ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT', u'physics_group_name': None, u'acquisition_era_name': 'CRAB', u'create_by': 'sdas', u'dataset_access_type': 'INVALID', u'data_tier_name': 'USER', u'last_modified_by': 'sdas', u'creation_date': 1424420874, u'processing_version': 1, u'processed_ds_name': 'sdas-glugluToX2000ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633', u'xtcrosssection': None, u'last_modification_date': 1424694677, u'dataset_id': 1046176, u'dataset': '/glugluToX2000ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT/sdas-glugluToX2000ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633/USER', u'prep_id': None, u'primary_ds_type': 'mc'}]

**Comment by HassenRiahi** [comment]
Thanks Yuyi for the check! I opened a CRAB ticket https://github.com/dmwm/CRABServer/issues/4689 to follow-up on task running over invalid datasets. Closing this ticket.
