### ISSUE TITLE
Add validFileOnly flag in dbs.listFileParents()  client call

### ISSUE THREAD

**Issue by ticoann** [dmwm/DBS#463]
I and Yuyi have different opinion on this but it is more convenience on our side to use it.
In WMAgent we only need process valid file so it is more convenient to get valid file in one call. Instead filtering out after getting all the data first.
Also it seems more consistent since other api provide validFileOnly flag. etc listFiles.

**Comment by yuyiguo** [comment]
I do not think this is relevant any more  because wmcore already has a patch. In addition, return only the valid file could cause confusing because a file does not have a parent is different from a file with an invalid parents file.
