### ISSUE TITLE
limits  list size for lumi, lfn, block lists

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#465]
We rewrote some the DAO objects in order to remove oracle limits on array binding for  lumi, lfn or block lists, but this also brings in a potential problem that when client sends a very log list to DBS, could oracle get the result in 5 minutes that is CMSWEB's server timeout time? Could the huge search bring down the oracle server?

We need to test where is the line for these very long lists? DBS client needs to break the query to several ones and the server should throw exceptions when the limits reached.

**Comment by yuyiguo** [comment]
@ticoann please add a list of block or dataset names that has a long list of lfn or lumi.

**Comment by ticoann** [comment]
Hi Yuyi, here are the some examples of blocks with 500 files

number of files  | block name
------------ | -------------
500 |  /WJetsToLNu_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#2bd8d5c4-d41f-11e4-908e-001e67abf518
500 |  /WJetsToLNu_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#34ff6b6e-d50e-11e4-908e-001e67abf518
500 |  /DYJetsToLL_M-50_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#608a9de2-d41b-11e4-908e-001e67abf518
500 |  /WJetsToLNu_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#6fcd2292-d5a2-11e4-908e-001e67abf518
500 | /QCD_Pt-15to3000_Tune4C_Flat_14TeV_pythia8/GEM2019Upg14DR-Phase1age1kMar26_PU140BX25_PH1_1K_FB_V2-v1/GEN-SIM-RECO#5450240e-d5a4-11e4-908e-001e67abf518
500 | /Pyquen_D0tokaonpion_Pt50_TuneZ2_Unquenched_2760GeV/HiFall13DR53X-NoPileUp_STARTHI53_LV1-v1/GEN-SIM-RECODEBUG#12525486-d046-11e4-a55c-001e67abf518
500 | /WJetsToLNu_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#08720638-d59f-11e4-908e-001e67abf518
500 | /DYJetsToLL_M-50_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#b4472f6e-d47e-11e4-908e-001e67abf518
500 | /WZjets_14TeV-madgraph-pythia6/TP2023SHCALDR-SHCALMar26_PU140BX25_PH2_1K_FB_V6-v1/GEN-SIM-RECO#74a3f1f8-daeb-11e4-bb3e-001e67abf518
500 | /WJetsToLNu_TuneCUETP8M1_8TeV-amcatnloFXFX-pythia8/Summer12DR53X-PU_S10_TuneCUETP8M1_START53_V19-v3/GEN-SIM-RAW#989503d6-d5b4-11e4-908e-001e67abf518
500 | /QCD_Pt-15to3000_Tune4C_14TeV_pythia8/TP2023SHCALDR-SHCALMar26_PU140BX25_PH2_1K_FB_V6-v1/GEN-SIM-RECO#b4efa172-d7bb-11e4-908e-001e67abf518

**Comment by yuyiguo** [comment]
Thanks @ticoann ,
How about dataset/block with huge  lumi sections?

**Comment by ticoann** [comment]
Hi Yuyi, I think there is a little confusion about huge lumi case. It is not that block or dataset contains huge lumis. We pass the user defined run lumi list to filter the dataset. So that is not related to certain dataset. Basically we can pass any numbers of argument here. (run and lumi)

https://github.com/dmwm/WMCore/blob/79dba9f7b62ceb0cea2d1625af883b9b828d2798/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L224

**Comment by yuyiguo** [comment]
@ticoann 
could you please let me know what is the limits on lfn, lumi, block and run you put in wma?

**Comment by ticoann** [comment]
We are slicing by 50 entries in agent now. (which is just a number we pick not considering optimal performance). You can use this function to slice the list in dbs client, if you want.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L570

**Comment by yuyiguo** [comment]
listFileArray wilt lfn list on cmsweb-tested:
time spent to query 1000 lfns is 0.363208. 
time spent to query 2000 lfns is 1.116449. 
time spent to query 3000 lfns is 1.416761.
time spent to query 1000 lfns is 0.355069. 
time spent to query 2000 lfns is 0.706697. 
time spent to query 3000 lfns is 1.076882. 

with lfn list and detail=1
time spent to query 500 lfns is 0.882571. 
time spent to query 1000 lfns is 0.480748. 
time spent to query 2000 lfns is 1.511340. 
time spent to query 3000 lfns is 2.292693.

with lfn list , detail=1 and run_num=10006: since none /store/mc data could not pass Lexicon.lfn function. I am using a none mc run num with MC data. So the output is 0. WE can see a lot of time is spent on transfering output to client. 
time spent to query 500/0 lfns is 0.171808. 
time spent to query 1000/0 lfns is 0.328159. 
time spent to query 2000/0 lfns is 0.672448. 
time spent to query 3000/3000 lfns is 1.888172.

**Comment by yuyiguo** [comment]
listFiles with dataset and long list of lumi:
37 seconds spent to fetch 2 lfns input lumi list length of 1311 listFile.
listFileArray with dataset and long list of lumi
6 seconds spent to fetch 1 lfns input lumi list length of 1311 using listFileArray.

**Comment by yuyiguo** [comment]
tested  listFileArray with lumi_list and dataset. The result shown are output/input-lumi-listlength
17/500 lumi used 4 seconds. 
 20/600 lumi used 9 seconds. 
 23/700 lumi used 7 seconds. 
 26/800 lumi used 12 seconds. 
 29/900 lumi used 16 seconds. 
 32/1000 lumi used 16 seconds. 
 39/1200 lumi used 247 seconds. 
 45/1400 lumi used 151 seconds. 
 52/1600 lumi used 204 seconds. 
 58/1800 lumi used 191 seconds.

**Comment by yuyiguo** [comment]
another run of lumi_list testing. The results varied a lot:
17/500 lumi used 4 seconds. 
 20/600 lumi used 7 seconds. 
 23/700 lumi used 17 seconds. 
 26/800 lumi used 17 seconds. 
 29/900 lumi used 14 seconds. 
 32/1000 lumi used 11 seconds. 
 39/1200 lumi used 20 seconds. 
 45/1400 lumi used 40 seconds. 
 52/1600 lumi used 22 seconds. 
 58/1800 lumi used 26 seconds.

**Comment by yuyiguo** [comment]
listFileArray on cmsweb with lfn list , detail=1 and run_num=10006: since none /store/mc data could not pass Lexicon.lfn function. I am using a none mc run num with MC data. So the output is 0. WE can see a lot of time is spent on 
time spent to query 500/0 lfns is 1.410486 second. 
time spent to query 1000/0 lfns is 0.694979 second. 
time spent to query 2000/0 lfns is 1.732970 second. 
time spent to query 3000/0 lfns is 1.621997 second .

**Comment by yuyiguo** [comment]
time spent to query 500/500 lfns w/o run is 1.667871. 
time spent to query 1000/1000 lfns w/o run is 0.897584. 
time spent to query 2000/2000 lfns w/o run is 1.376286. 
time spent to query 3000/3000 lfns w/o run is 1.592051.

time spent to query 500/0 lfns with run=10006 is 0.218780. 
time spent to query 1000/0 lfns with run=10006 is 0.398238. 
time spent to query 2000/0 lfns with run=10006 is 0.683651. 
time spent to query 3000/0 lfns with run=10006 is 1.060255. 

time spent to query 500/444 lfns with run=1 is 0.845584. 
300.153774977
HTTP Error 502: Proxy Error

So with run_num=1, 1000 lfns caused timeout.

**Comment by yuyiguo** [comment]
Need to add unit tests on client API split calls.

**Comment by yuyiguo** [comment]
Done.
