### ISSUE TITLE
Check for datatiers 

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#466]
@ericvaandering,  @ticoann,  @belforte 
DBS Block/bulk insert API will automatically insert a new tier into DBS when a dataset is inserted with a new tier. This was a requirement from WM. There were two reasons for this: 1. The datatier from WMA was always valid because this was a well controlled application. 2. If DBS rejected a dataset because its datatier was not in the DB, it would fail the job and it was in  the late stage of a job process. Reprocessing the data because someone forget to pre-register a datatier was considerate a price too high to pay. 

However, when we use the same API to publish user data, the datatier could be anything. These datasets might be migrated into PROD DBS later. So we have to introduce the check of datatier some where in the system to make sure the production DB is not polluted by testing data. 

There are several ways we can make sure the PROD only holds valid datatiers. I would like keep the block/bulk insert API as it is because failing it in last minutes is too late, but check the datatier before giving it to DBS or during the physics  DBs to PROD migration.

1. Check it in WMA  before it send to DBS . @ticoann, can you check if WMA already does it? if not, would be easy for you to do it?
2. Can Crab check it too, @belforte ? 
3. Check it in DBS migration server, if a datatier is not already in destination, we will fail the migration. This way the failure has no impact on WMA.

**Comment by ericvaandering** [comment]
Seems like #3 gets us the behavior we want. 

Eric


> On Apr 20, 2015, at 09:46, Yuyi Guo <notifications@github.com> wrote:
> 
> @ericvaandering <https://github.com/ericvaandering>, @ticoann <https://github.com/ticoann>, @belforte <https://github.com/belforte> 
> DBS Block/bulk insert API will automatically insert a new tier into DBS when a dataset is inserted with a new tier. This was a requirement from WM. There were two reasons for this: 1. The datatier from WMA was always valid because this was a well controlled application. 2. If DBS rejected a dataset because its datatier was not in the DB, it would fail the job and it was in the late stage of a job process. Reprocessing the data because someone forget to pre-register a datatier was considerate a price too high to pay.
> 
> However, when we use the same API to publish user data, the datatier could be anything. These datasets might be migrated into PROD DBS later. So we have to introduce the check of datatier some where in the system to make sure the production DB is not polluted by testing data.
> 
> There are several ways we can make sure the PROD only holds valid datatiers. I would like keep the block/bulk insert API as it is because failing it in last minutes is too late, but check the datatier before giving it to DBS or during the physics DBs to PROD migration.
> 
> Check it in WMA before it send to DBS . @ticoann <https://github.com/ticoann>, can you check if WMA already does it? if not, would be easy for you to do it?
> Can Crab check it too, @belforte <https://github.com/belforte> ?
> Check it in DBS migration server, if a datatier is not already in destination, we will fail the migration. This way the failure has no impact on WMA.
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/DBS/issues/466>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by yuyiguo** [comment]
Checked with Seangchan. T0 controls what tiers to put in the DBS. it is well managed on the T0 side. There are eight tiers allowed and they registered to DBS already. Should we allow any new tiers from user data? Should user data tiers be predefined too?

**Comment by ticoann** [comment]
Hi Yuyi,

> Check it in WMA before it send to DBS . @ticoann, can you check if WMA already does it? if not, would be easy for you to do it?

Actually we don't really check the tier whether that is correct tier or not. Tier0  tightly control (hard coded) which tier is allowed. But WMAgent not validating whether is correct tier or not. We can add that in the validation when request is created. The only concern is when new the new tier is introduced, I think we need to able to handle that in short notice. (not waiting the cms deployment schedule)

**Comment by ericvaandering** [comment]
Tier0 cannot determine all the Tiers. It certainly doesn’t do anything with “SIM” in it nor, I assume, mini AOD tiers.


> On Apr 20, 2015, at 10:31, Yuyi Guo <notifications@github.com> wrote:
> 
> Checked with Seangchan. T0 controls what tiers to put in the DBS. it is well managed on the T0 side. There are eight tiers allowed and they registered to DBS already. Should we allow any new tiers from user data? Should user data tiers be predefined too?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/DBS/issues/466#issuecomment-94484498>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by belforte** [comment]
I like that users can not write to PROD, but in the end we can not think of "phys03" as a junkyard. Remember that most migrations go the other way, in the end all useful data is listed in phys03.
Nor is a good reason to get an oddly named tier in PROD due to a typo in a workflow !
I can surely understand the history of how we go here, but maybe we can still improve.

Best solution IMHO is:
1. we list valid Tiers (in Lexicon.py)
2. WMA, ReqMgr, Prep, CRAB ...all that check and validate that EARLY, do not rely on DBS server to barf at the end of the workflow
So I will do that for CRAB. And if production ever does the same, then we will be able to put the check in DBS server as well and make sure database stays clean.

Stefano

**Comment by yuyiguo** [comment]
OK, new tiers created after T0. 
Seangchan, adding a new tier does not CMSWEB release. Just a sql command.

**Comment by belforte** [comment]
we can think of moving the list of valid tiers off the code.

**Comment by yuyiguo** [comment]
I agree that we cannot treat "phys03" as a junkyard.

I my think that valid tiers stays in the DB instead of code. There is DBS API to list all the tiers. Can WMA and Crab call this API during the time PREPPARE for the bulk/block data?

If indeed a new data tier is needed, I can just insert it into the DB without waiting for any code update.

**Comment by ticoann** [comment]
Yes, we can use the service DBS (or something else) provide for tier validation.

**Comment by belforte** [comment]
Sounds good. Anyhow it is not urgent, currently CRAB forces tier = USER, we will add NOTEDM  and will see in time about publication with user script.
Passage of datasets from phys03 to PROD can't be done by user anyhow. 
On Apr 20, 2015 5:54 PM, Yuyi Guo <notifications@github.com> wrote:I agree that we cannot treat "phys03" as a junkyard.

I my think that valid tiers stays in the DB instead of code. There is DBS API to list all the tiers. Can WMA and Crab call this API during the time PREPPARE for the bulk/block data?

If indeed a new data tier is needed, I can just insert it into the DB without waiting for any code update.

**Comment by yuyiguo** [comment]
@belforte , is crab ready for inserting tier into DBS if new tier appears before sending data to DBS for block/bulk insertion?
Talked with @ticoann  yesterday, WMA is ready since there is no new data tiers needed. I think WMA still need to check.

If crab is ready I am going to remove automatic tier insertion in block/bulk insert API as well as in the migration in June release. Please let me ASAP.

**Comment by belforte** [comment]
so far CRAB2+3 only writes with tier=USER
We never create tiers !
any plan for other tier name there is only chat.


On 05/15/2015 08:11 PM, Yuyi Guo wrote:
> @belforte <https://github.com/belforte> , is crab ready for inserting tier into DBS if new tier
> appears before sending data to DBS for block/bulk insertion?
> Talked with @ticoann <https://github.com/ticoann> yesterday, WMA is ready since there is no new data
> tiers needed. I think WMA still need to check.
>
> If crab is ready I am going to remove automatic tier insertion in block/bulk insert API as well as
> in the migration in June release. Please let me ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/DBS/issues/466#issuecomment-102475405>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by yuyiguo** [comment]
Ok. I am going to change DBS since no one is going to insert new tiers in near future. But I still recommend  that both crab and WMA check the tier in the code . If you have new tiers, please let me know and I will insert them. Any one with insert privilege can insert them too.

**Comment by belforte** [comment]
Dinitely. You can be sure that CRAB will be very careful in this. Thanks

**Comment by yuyiguo** [comment]
Done with coding API and unit tests

**Comment by yuyiguo** [comment]
Done.
