### ISSUE TITLE
Inconsistent usage of max_list_len between client and server

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#485]
It seems we have an inconsistent usage of this max_list_len (for lumi_list for instance) between dbs client and server.

In the dbsClient code, we check the length of the list regardless whether it's a plain or a nested list (cannot be bigger than 1000, otherwise we slice it):
https://github.com/dmwm/DBS/blob/d58e4fe7be87a6f84da4f246523641c9988ba1ef/Client/src/python/dbs/apis/dbsClient.py#L1009

on the server side, we first expand this lumi_list in a plain list and then AND only then we check it against
the max length
https://github.com/dmwm/DBS/blob/00f44b9b32cefd79888eb1ded0ab8e359ab47965/Server/Python/src/dbs/web/DBSReaderModel.py#L910

where the following nested list
[[248, 494], [534, 546], [638, 650], [794, 1313], [1327, 1339], [1353, 1482], [1496, 1573], [1652, 1664], [1743, 1755], [1860, 1872]]

has 1053 elements, thus DBSServer returns a Bad Request.

Before putting more effort on it, I'd like to know whether we should fix it on the DBS side
a. checking their length before any expansion
b. if passes previous test but it's bigger, either go ahead or slice on the client side
or fix it in WMCore
a. always expand from range of lumis to a plain lumi list and make POST calls with this plain list.

Yuyi, if needed, you can see more details in https://github.com/dmwm/WMCore/issues/6241
@ticoann FYI

**Comment by ericvaandering** [comment]
Since the client already has the slicing and just seems to be doing it on the wrong set of values, it seems it should be quite easy to add the correct slicing algorithm to DBSClient. It seems very hacky to me to try to add yet another set of slicing into the agent.

**Comment by yuyiguo** [comment]
Alan:

If it is convenient to you, could you give me the data block that has this long list of lumis?

**Comment by amaltaro** [comment]
It should be
/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE

**Comment by yuyiguo** [comment]
More question which run the lumis belong to?

**Comment by amaltaro** [comment]
It's MC, so run 1. Just in case, this is one of the requests:
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_HIG-RunIISummer15GS-00012_00069_v0__150909_001759_8054

**Comment by yuyiguo** [comment]
[{'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/509BAA93-35DD-E411-B5BB-002618943933.root'}, {'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/722ADB9D-35DD-E411-9CCD-0025905B8592.root'}, {'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/A6A86FA9-33DD-E411-A03B-001E67A400F0.root'}, {'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/6AF5D490-35DD-E411-A812-0025905A60D6.root'}, {'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/3C52C78D-35DD-E411-A03D-0025905B8572.root'}, 
It looked working to me.
With 
dataset =  "/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/RunIIWinter15wmLHE-MCRUN2_71_V1-v1/LHE"
run_num=1
lumi_list=[[248, 494], [534, 546], [638, 650], [794, 1313], [1327, 1339], [1353, 1482], [1496, 1573], [1652, 1664], [1743, 1755], [1860, 1872]]

I found below files:

{'logical_file_name': '/store/mc/RunIIWinter15wmLHE/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/LHE/MCRUN2_71_V1-v1/10000/18C6BFE9-39DF-E411-ADAD-0025904C669C.root'}]

**Comment by yuyiguo** [comment]
Done.

**Comment by amaltaro** [comment]
Thanks Yuyi!
