### ISSUE TITLE
Very slow response for listFileArray

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#505]
Hi Yuyi,

we've just hit another problem (timeout) in central production when querying listFileArray() api with a lumi_list. Basically in this line:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L224-L225

Central workqueue was timing out everytime it was trying to handle this request
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_task_SUS-RunIISpring15FSPremix-00166__v1_T_151128_061037_6440

which has a total of 35k lumis in the mask. As you can see, WMCore is creating slices of 50 lumis for each query and even so some of those calls were failing (from Nov 29 until yesterday).

I made this quick script
https://github.com/amaltaro/ProductionTools/blob/master/timeDBSLumis.py
to replicate the issue and to time some of these calls, the results are that it may take from 5 secs to ~70 secs. Querying for 10k lumis took 3.3k secs today (the situation was way worse yesterday).

Do you have any suggestions how we could improve it? If I try querying with a lumi_list length of 10k lumis, it will just timeout.

@ticoann @julianbadillo FYI

**Comment by yuyiguo** [comment]
Hi, Alan:

I looked at your example code that reproduced the issue. You had run num 1 in the sample code. Was the production also using run num 1? If so, this was the problem. Because all CMS MC runs have run num 1. So this query was doing a full table scan in the biggest DBS table (run lumi table). In principle, this API should disable run num 1 with lumi together search.

Could you explain your use case so we can find other ways to query DBS?

Yuyi

**Comment by amaltaro** [comment]
The general use case is the following:
 I want to process only a subset of a dataset, and that subset is represented by a lumiList with run+lumis key/value pairs. For this case, workqueue and WMAgent have to call dbs and retrieve blocks that contain at least one lumi section from my lumiList (belonging to the same run, of course). Provided the blocks, it goes through all the files and make a mapping of run and lumis.

Are you suggesting the following:
 1. for MC datasets: in this case we should call listFileArray() providing only the dataset and lumi_list, but not the run_num, since the default (in 99.5% of the cases) is run_num=1
 2. for data datasets: we must provide the run_num, including lumi_list when needed. So we cannot modify anything in this case.
?

**Comment by yuyiguo** [comment]
No, I did not suggest above 1 or 2.

I think below steps may help. You may want to test it in a sample script.
1.  find all blocks in the given dataset.
2. loop all blocks with  listFileLuims(block_name=b)
3. compare you lumi list with what you get from 2 , then you will find the blocks you want to process.

We can talk about it in today's meeting.

**Comment by amaltaro** [comment]
Yuyi,
I just noticed run_num parameter is *mandatory* when we provide lumi_list. You may want to
fix it as well to default to 1 when it's not passed, otherwise there is no way to optimize this call from the WMCore side.

**Comment by yuyiguo** [comment]
Alan:

Yes. run_numis mandatory when any lumi is present. This is true to any DBS APIs. I will check if it is default to 1. We cannot have it to default to 1. If run number is missing, it should return to user as a input error.

**Comment by amaltaro** [comment]
Ok, I'm running some tests with a much smaller dataset now - in testbed - and it seems to be in a pretty bad shape (still using the same code, basically to make sure the new code gets the same results).
The testbed db is much much smaller and I didn't expect this slowness at all, 8 out of 10 queries (for dataset + run=1 + 25 lumis.

I'm testing the block by block code now.

**Comment by amaltaro** [comment]
Yuyi, as you can see, a patch has been created.

Still on the performance subject, I made these 2 small scripts where you can play with and do some additional performance tests on your side (maybe there is something in this api that could be improved on the server side):
https://github.com/amaltaro/ProductionTools/commit/b81dc7dea036da81d69c9ca9d91653e89df528bc

In summary, querying by blocks is much faster. However, I still think it's safer to keep the slicing in WMCore. Otherwise we may get very long lumi_lists and that would time out in DBS (especially the first query, the others go quicker). Just in case, these were my 2 examples/measurements without slicing:
```
cmst1@vocms009:/data/srv/wmagent/current $ python timeDBSLumisBlock.py 10000
Script started at 2015-12-09 09:28:24.367578
Querying for blocks in the dataset at 2015-12-09 09:28:24.449383
Querying each block now at 2015-12-09 09:28:24.724596
  block query completed in 0:03:10.912516
  block query completed in 0:00:21.770946
  block query completed in 0:00:04.041114
  block query completed in 0:00:03.904078
  block query completed in 0:00:03.886872
  block query completed in 0:00:03.970234
  block query completed in 0:00:04.078350
  block query completed in 0:00:05.875717
  block query completed in 0:00:04.125823
  block query completed in 0:00:04.847408
  block query completed in 0:00:05.250547
  block query completed in 0:00:04.006138

Starting queries to listFileLumis at 2015-12-09 09:32:41.397589
/SMS-T5qqqqVV_mGluino-1200To1275_mLSP-1to1150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIWinter15pLHE-MCRUN2_71_V1-v1/LHE#08a23cc4-91a4-11e5-ad9f-002590494c06
  query completed in 0:00:00.193997
Lumis: 10000	Seconds: 257.211137056
```

and
```
cmst1@vocms009:/data/srv/wmagent/current $ python timeDBSLumisBlock.py 20000
Script started at 2015-12-09 09:33:05.037853
Querying for blocks in the dataset at 2015-12-09 09:33:05.050629
Querying each block now at 2015-12-09 09:33:05.914665
  block query completed in 0:04:28.527552
  block query completed in 0:00:22.901967
  block query completed in 0:00:08.017349
  block query completed in 0:00:08.204277
  block query completed in 0:00:09.200588
  block query completed in 0:00:08.461543
  block query completed in 0:00:09.124061
  block query completed in 0:00:07.921858
  block query completed in 0:00:07.200667
  block query completed in 0:00:09.027430
  block query completed in 0:00:08.617765
  block query completed in 0:00:08.533592

Starting queries to listFileLumis at 2015-12-09 09:39:21.656046
/SMS-T5qqqqVV_mGluino-1200To1275_mLSP-1to1150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIWinter15pLHE-MCRUN2_71_V1-v1/LHE#08a23cc4-91a4-11e5-ad9f-002590494c06
  query completed in 0:00:00.186076
/SMS-T5qqqqVV_mGluino-1200To1275_mLSP-1to1150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIIWinter15pLHE-MCRUN2_71_V1-v1/LHE#cfdbb83e-91a8-11e5-ad9f-002590494c06
  query completed in 0:00:00.737411
Lumis: 20000	Seconds: 377.540220976
```

**Comment by yuyiguo** [comment]
Alan:

I will look into this on Monday. I am in training until Friday.
Yuyi

**Comment by yuyiguo** [comment]
API updated to require searching on run_lum=1 must provide lfns. Closed.

**Comment by amaltaro** [comment]
Yuyi, I don't think I followed your comment. 

Are your saying that listFileArray() API now requires a run number to be passed every time a lumi list is provided? Is there any other mix of parameters that would make run_num mandatory as well? For the sake of clarity, you could illustrate it with a few examples. 

If this is a breaking change, then we may need to update WMCore code for tomorrow...

**Comment by yuyiguo** [comment]
Alan:

Searching on  lumi list always requiring a associated run number in DBS. This is not new, but always in DBS. If you did not have problem before that means you have already been doing right thing.  
The change I made from last release was require LFNs when a listFileArray is called with a lumi list and run_num=1, This has been in production for a few months. I forgot closing this issue.

There are two dozen examples of using this API in DBS unittests. https://github.com/dmwm/DBS/blob/master/Client/tests/dbsclient_t/unittests/DBSClientReader_t.py#L485

**Comment by amaltaro** [comment]
Thanks, Yuyi. If it's in production for a few months already, then we should be Ok indeed.
