### ISSUE TITLE
Blocks migration is taking too long

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/DBS#514]
The dataset is: /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM

It seems that the migratrion of the following 4 blocks from the global to phys03 is taking days. Is it expected?

/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM#3b842b96-ccac-11e5-92d9-001e67abef8c
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM#52470c42-ccf0-11e5-ac46-a0369f23cf8a
 /DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM#782b5ea4-cca5-11e5-92d9-001e67abef8c
/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/RunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1/MINIAODSIM#9bda7aca-ccea-11e5-ac46-a0369f23cf8a

**Comment by belforte** [comment]
e.g. the first block in the list is actually in Phys03 now [1]
what exactly does ASO see about this ?
[1]
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=block%3D%2FDYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1%2FMINIAODSIM%2352470c42-ccf0-11e5-ac46-a0369f23cf8a

**Comment by belforte** [comment]
here's the migration status [1]
indeed they are all listed as in progress [2]
but the dataset is fully migrated [3]

Need @yuyiguo to have a look at migration logs :-(


[1]
>>> migrationIds
[1690130, 1690119, 1690121, 1690125]
>>> for id in migrationIds:
        status = apiMig.statusMigration(migration_rqst_id=id)
        state = status[0].get("migration_status")
        retry_count = status[0].get("retry_count")
        print "migration id, state, retries : %d %d %d" % (id, state, retry_count)

... ... ... ... ... migration id, state, retries : 1690130 1 0
migration id, state, retries : 1690119 1 0
migration id, state, retries : 1690121 1 0
migration id, state, retries : 1690125 1 0
>>> 

[2]
https://cms-http-group.web.cern.ch/cms-http-group/apidoc/dbs3-client/current/dbs.apis.html

[3]
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset%3D%2FDYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8%2FRunIIFall15MiniAODv2-PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext4-v1%2FMINIAODSIM

**Comment by belforte** [comment]
I have to correct myself, only 61 out of 65 blocks are in phys03.
The 4 missing blocks are the 4 ones listed by Hassen.

and I misread DAS output when I wrote that block was present in Phys03 in my first comment :-(

**Comment by yuyiguo** [comment]
Hi, all:

I was off yesterday. My investigation showed that the problem was caused the machine had memory problem during the middle of migration and DBS migration server had to restarted. So the migration processes started by the previous server became a orphans that states at status 1 forever.

Any idea when will cmsweb production nodes will stop the memory swap?

**Comment by belforte** [comment]
thanks Yuyi, can we somehow retrigger those migrations then ?
I do not know what's the status with cmsweb nodes, a problem with crabserver should have been fixed in the release installed last week but nodes keep crashing and I do not now if anybody has identified which service is creating the problems, i.e. if the crabserver issue was not solved of if something else it at play.

**Comment by yuyiguo** [comment]
@belforte 
@HassenRiahi 

I manually migrated these four blocks and their parents. Please check and let me know if there are still problems.

**Comment by HassenRiahi** [comment]
Thanks Yuyi. It works fine now. All outputs of the user have been published correctly.

**Comment by yuyiguo** [comment]
done.
