### ISSUE TITLE
Add DBS client to pypi

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/DBS#540]
Greetings, DBS developers -- 

I would like to add the bits to get the DBS client put into pypi (https://pypi.python.org), so it can be more easily used by other projects. I've got a similar PR/issue for WMCore: https://github.com/dmwm/WMCore/issues/7647

The change to DBS itself would mostly revolve around updating setuptools to have the correct version: https://github.com/dmwm/DBS/blob/master/setup.py#L331 and an addition to the DMWM jenkins intance to automatically publish new tags as they're produced.

Would this be amenable to you?

**Comment by yuyiguo** [comment]
It is fine with me if you can take care the package since I am not familiar with pypi at all.  Did you mean the change was https://github.com/dmwm/DBS/blob/master/setup.py#L330 to get the correct version number there not L331, right?  As you can see that we did not update that version number because it was not used. But I can update it staring now.

**Comment by PerilousApricot** [comment]
Yeah, that's what I mean. Pypi depends on the version (in `setup()`) being incremented before the tag is produced. For WMCore, I was able to find somewhere that the version was set, but I couldn't find anything similar with DBS.

If you can have it automatically set with whatever script you use to make a new release, that would be great and solve my problem.

**Comment by yuyiguo** [comment]
I understood that you want to have DBS client, right? I have client version specified  at https://github.com/cms-sw/cmsdist/blob/comp_gcc493/dbs3-client.spec#L1. This is used to build the rpm. What you pointed was DBS server setup.

**Comment by PerilousApricot** [comment]
Yeah, but unfortunately the actual `setup()` call in `setup.py` needs to change. I can't sidelink a separate repo for it.

**Comment by yuyiguo** [comment]
OK. I will find way to update https://github.com/dmwm/DBS/blob/master/setup.py#L331 before I tag a new release.

**Comment by PerilousApricot** [comment]
If you see the PR I have against WMCore above, it looks for WMCore.__version__ which is bumped by bin/buildrelease.sh . Might be a good starting point

**Comment by yuyiguo** [comment]
@PerilousApricot 

Looked at WMCore code (https://github.com/PerilousApricot/WMCore/blob/master/setup.py#L115), but I did not get how the __version__ was automatically updated. 

On the other hand, DBS has client and server two parts,  the version of server and client will not always the same.  https://github.com/dmwm/DBS/blob/master/setup.py#L330 is the dbs server version.  Do you really want to use it for the client?

**Comment by yuyiguo** [comment]
@PerilousApricot 

Is this still a valid issue?  Do you still want DBS client in pypi?

**Comment by PerilousApricot** [comment]
For definite. Sorry, it's hard to keep up with github notifications, there's a lot of noise. From here I see that we need a versionstring that's bumped on every release.

**Comment by bbockelm** [comment]
Hi Yuyi,

Where is the DBS client release procedure documented?  Is it a script (as in WMCore) or documented on a wiki page?

Brian

**Comment by yuyiguo** [comment]
DBS Client is released with the server together. There is no separated release procedure.

**Comment by bbockelm** [comment]
That's fine.  Where is the DBS release procedure documented currently?

**Comment by yuyiguo** [comment]
Release is done by HTTP group.  They must have their procedure to release all the services. I don't see DBS is special.  I don't know where they document them.

**Comment by yuyiguo** [comment]
Here is the monthly CMS web release process that I believe very service follows currently:
1. Lina created a HGYYMM request  as in below:
https://gitlab.cern.ch/cms-http-group/doc/issues?scope=all&utf8=%E2%9C%93&state=closed
2. Each service provider will decide if they need a new release or not. For DBS, if I need a new release, I will put as much as issues into it or I will do a emergency release to have only the most important issues to it. As usually, there are more than one round I will go through,  update DBS code and deploy script, configure and etc, build and tested on my vm until I  am happy with it. 
3. Then I will tag and update Lina's request tk with a PR and a list of things I did in the release.
4. Lina collects everything before her pre-prod deadline, then push to the pre-prod.
5. Everyone tested against the pre-prod. I will test DBS with the same unit, validation and release tests as I did on my VM. If there is major changes, I will ask crab and agent to do their tests as well.
6. Sometimes, we found problem during the pre-prod period. We will repeat 2-5 until every tests were successful.
7. Lina will push the same version on pre-prod to prod.

As I said , there is no special for DBS in the CMSWEB release. everything is documented on github, as issues and tags. We already have a version number while building and deploying a release. But we don't do this for client separately.

**Comment by bbockelm** [comment]
Hi Valentin,

For now, can we keep the scope as the DBS client?

It seems all we need to do is to put the version number in the code itself and make sure to bump it in the release.

Would it be possible to put a sanity check in the cmsdist code to make sure the version number matches the git tag?

Brian

**Comment by PerilousApricot** [comment]
Checking up on this -- There's a difference between HTTP group releases and DBS releases. They may happen at the same time, but they're decoupled -> DBS can release a new version of their packages, but that doesn't necessarily imply that HTTPG will pick it up.

For now, all that needs to happen is that whenever DBS cuts a new release (let's call it 2.0.1b), the __VERSION__ string needs to be updated to 2.0.1b, and a new tag needs to be made. What do we need to do to make that happen?

This is part of what CMSDIST uses to build RPMs-
https://github.com/cms-sw/cmsdist/blob/comp_gcc493/dbs3-client.spec#L1, the only difference from now is that the __VERSION__ in the repository needs to be updated as well.

**Comment by PerilousApricot** [comment]
(I wanted `__VERSION__` instead of the bold versions above)

**Comment by vkuznet** [comment]
A basic solution should be the following:
- add `__VERSION__` string to dbs codebase
- modify setup.py script install clause to replace `__VERSION__` with git tag one such that when you'll do
```
python setup.py install
```
it will call a function from setup.py to replace `__VERSION__` with git tag and install code in user-based area with concrete tag.
