### ISSUE TITLE
HTTP Error 502 when inserting a block

### ISSUE THREAD

**Issue by belforte** [dmwm/DBS#543]
we have hit a very odd error when publishing a user dataset in DBS/phys03 with ASO.
The call to `insertBulkBlock` returns with:
```  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 320, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 194, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 218, in __parseForException
    raise http_error
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 502: Bad Gateway

```
Other blocks for same dataset and same user went OK, just like other datasets for this user and everything for other users. This is the first time we get such an error.

Can you find out what the reason for the problem is ? I suspect something peculiar in the block makes the client send a malformed request to the server, but there is nothing so obviously wrong that I can spot it. Note that while this block has only 50 files, it has a list of 480k lumis. The "string" version of the block is 160MB.

The problem can be reproduced standalone. I attach the block in ASCII format (gzipped for space) as extracted from ASO log
[block.txt.gz](https://github.com/dmwm/DBS/files/906223/block.txt.gz)

a simple set of python lines which reads it and reproduces the problem is pasted below, the above file needs to be gunzipped into `block.txt`
```
# read printed block
with open("block.txt") as fp: blockString=fp.read()

# this has a newline at the end, remove it
blockString=blockString[:-1]

# read the string into a dictionary (takes a while)
blockDict=eval(blockString)

print blockDict.keys()

# check that it is a good block for insering in DBS

print blockDict['dataset_conf_list']
print blockDict['dataset']
print blockDict['primds']
print blockDict['acquisition_era']
print blockDict['processing_era']
print blockDict['block']
print len(blockDict['file_conf_list'])
print blockDict['file_conf_list'][0]
print len(blockDict['file_parent_list'])
print blockDict['file_parent_list'][0]
print len(blockDict['files'])
print blockDict['files'][0].keys()
print blockDict['files'][0]['check_sum']
print blockDict['files'][0]['adler32']
print blockDict['files'][0]['event_count']
print blockDict['files'][0]['file_type']
print blockDict['files'][0]['file_size']
print blockDict['files'][0]['logical_file_name']
print len(blockDict['files'][0]['file_lumi_list'])
print blockDict['files'][0]['file_lumi_list'][0]
print blockDict['files'][0]['file_lumi_list'][-1]


# DBS part

from dbs.apis.dbsClient import *
destUrl="https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter"
readUrl="https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader"
blockDict['block']
destApi=DbsApi(destUrl)
readApi=DbsApi(readUrl)

readApi.serverinfo()


dataset=blockDict['dataset']['dataset']
print dataset

block2insert=blockDict['block']['block_name']
print block2insert

blocks=readApi.listBlocks(dataset=dataset)
print len(blocks)


destApi.insertBulkBlock(blockDict)

# and now I get:
"""
>>> destApi.insertBulkBlock(blockDict)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 320, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump, callmethod='POST' )
  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 194, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/asyncstageout/v1.0.7pre1/sw.pre.dciangot/slc6_amd64_gcc493/cms/dbs3-client/3.3.153/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 218, in __parseForException
    raise http_error
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 502: Bad Gateway
>>>
"""
```

**Comment by belforte** [comment]
I forgot to say that many blocks for this user/dataset fail in this way. THis is just the first that we could grab and test.
It is very strange...
FWIW the thread with the user is in
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2772/1/1/2.html

**Comment by yuyiguo** [comment]
I am investigating the problem.

**Comment by yuyiguo** [comment]
@belforte 
I was trying to load it to my VM so I could debug the problem. However, I could run the code on my VM. As soon as the code run to  blockDict=eval(blockString) I got "Killed" . I tried to use literal_eval and made no difference. The file was too big to run.  I am trying to find different way to get the input.

**Comment by yuyiguo** [comment]
@belforte 
Does the troubled block have the biggest lumi list  so far?

**Comment by belforte** [comment]
I have no idea if that's the biggest lumi list !
Sorry about eval, I had tried to use the codeImport from the test in dbs client repo, but could not make it to work by simply copy/pasting into my interactive python and had to look for something that I could somehow understand. 
I guess we can try to cut into smaller blocks, if I were a real developer I would have probably done it in the time it takes me to write a mail. But things being what they are... better if someone else does it.

**Comment by belforte** [comment]
THe process where I run python and load that dictions is using 3GB of RAM.
No wonder your VM struggles.

**Comment by yuyiguo** [comment]
I don't know how you generated the block.txt. It is huge string, so cannot be edited. It is single quota, it can be  handled as json ...

**Comment by belforte** [comment]
I think Diego C. put a print statement in the ASO publisher. @dciangot ?
Indeed it is huge

>>> print blockDict['block']['block_size']
69999718050

**Comment by belforte** [comment]
OTOH:  50 files
>>> print len(blockDict['files'])
50
But looking better, it was 48k lumis in first file only:
>>> print len(blockDict['files'][0]['file_lumi_list'])
48000
>>> 
for a total of 2.4M lumis
>>> tl=0
>>> for file in blockDict['files']:tl += len(file['file_lumi_list'])
... 
>>> tl
2400000

now a good question could be: is that real, or did we mess up lumi accounting ?

But first thing is to tell if this is really the reason of the error.

**Comment by yuyiguo** [comment]
I changed the text file into a python module so I can directly load it without convection. However, my VM still could not have enough memory to handle the file. We have to move to the testbed to debug the problem. But I want to ask you guys check how you got such big number of of lumis.

What was the lumis per file for each the 50 files? What is runs per file for all the files? 
Thanks,
Yuyi

**Comment by belforte** [comment]
this is a user-produced SIM with PU on top of some MC.
I suspect an unrealistically large amount of lumi was
used e.g. in the MC production.
But the thing is that those are user datasets, we have
no control and do not really know what they do.

**Comment by belforte** [comment]
OTOH:  50 files
>>> print len(blockDict['files'])
50
But looking better, it was 48k lumis in first file only:
>>> print len(blockDict['files'][0]['file_lumi_list'])
48000
>>> 
for a total of 2.4M lumis
>>> tl=0
>>> for file in blockDict['files']:tl += len(file['file_lumi_list'])
... 
>>> tl
2400000

now a good question could be: is that real, or did we mess up lumi accounting ?

But first thing is to tell if this is really the reason of the error.

**Comment by belforte** [comment]
well, if it were data, 2.4M lumisection at 93sec each would be 7 years. Clearly it is an oitrageous number for a single block.
Do you think the huge number of lumis is the reason for the error ?

**Comment by belforte** [comment]
I looked at already published blocks in this dataset [1]. All of them have an
astonishing number of lumis, but none is as large as the one triggering the hppt 502 error.

[1]
```
>>> dataset="/QCD/anstahll-Embedded_Pythia_QCD_PtHat20_MuEnrichedPt15_8160GeV_pythia8_reverse_RAW_20170403-1939edae70a88024edac0d6bcb9b5150/USER"
>>> blocks=readApi.listBlocks(dataset=dataset)
>>> print "#files\t#events\t#lumis"
#files	#events	#lumis
>>> for block in blocks:
...   summary = readApi.listFileSummaries(block_name=block['block_name'])[0]
...   print "   %d\t%d\t%d" % (summary['num_file'], summary['num_event'], summary['num_lumi'])
... 
   1	888	48000
   1	891	48000
   1	844	48000
   1	896	48000
   13	11317	624000
   5	4317	240000
   5	4302	240000
   1	848	48000
   1	855	48000
   16	13788	768000
   31	27218	1488000
   19	16588	912000
   2	1718	96000
   1	838	48000
   5	4330	240000
   3	2596	144000
   1	928	48000
   6	5341	288000
   45	39209	2160000
   11	9675	528000
   12	10367	576000
   1	897	48000
   2	1804	96000
   1	854	48000
   2	1666	96000
   3	2590	144000
   1	813	48000
   11	9507	528000
   5	4361	240000
   1	881	48000
   4	3497	192000
   1	892	48000
   9	7834	432000
   14	12355	672000
   1	911	48000
   1	966	48000
   1	893	48000
   1	865	48000
   1	834	48000
   2	1728	96000
   1	896	48000
   1	916	48000
   3	2605	144000
   2	1770	96000
   1	945	48000
   6	5261	288000
   3	2696	144000
>>> 
```

**Comment by belforte** [comment]
Assuming that the problem is really in the number of lumis in one block, i have sent the following message to the user.
@yuyiguo I think what we need from you is the confirmation that the bad gateway error is really due to this, and then some sanity limits on the block to be published, so that we can check against those early and either break the block into smaller units or halt the processing and bump things back to the user.

```

*** Discussion title: Computing Tools

Andre, it is very likely that they problem is the huge number of lumis.
Your input dsataset has 6k lumis per file (vs. 100 events ! so they are
almost all empty).
In the CRAB task you process 8 files per job, so the output dataset has 48k
lumis per file.
Most of the times CRAB/ASO published blocks with a few files, and things
where OK.
But when a 50 file block arrived, it has inside an overall list of 2.4M
lumis, which is very likely to be what's making DBS server choke,
In real life one lumi is 93seconds, and 2.4M lumis mean 7 years of data. No
wonder that it never happened so far, nor that DBS is not prepared to
digest all of that in a single block.

I will pursue the thing with DBS developers, since if that's indeed the
(only) problem, we could generate a clear error message much earlier, but
in the meanwhile, I have to suggest that you redo this production starting
from a new GEN sample with a more appropriate number of lumis.

Stefano

-------------------------------------------------------------
Visit this CMS message (to reply or unsubscribe) at: 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2772/1/1/3.html

```

**Comment by yuyiguo** [comment]
@belforte
" 2.4M lumisection at 93sec each would be 7 years. " The 93sec/lumi was the lumi length, right?

As you mentioned, there were only 6k lumis per file but only 100 events. Most of them were empty. Is it necessary to write empty lumi in the results? 

There were 2.16M in one of the blocks published above.  If there is a limit on lumi size, it may be close to 2.4M. We need to verify this. I will try to get direct access to cmsweb testbed to test it since my VM will not be able to do it.  May I ask you a favor that you run the insertion again when I watch the server?

**Comment by belforte** [comment]
Yes, each luminosity section (aka lumi) in data taking is
currently 93 seconds.
lumis w/o events need to be listed in data in order to
properly account for machine luminosity, but for MC (like in this case)
I think not (at least so far nobody has used lumis to keep track
of MC luminosity, they have been introduced in generated data
mostly as a handle for job splitting in processoing).
I suspect the user did not realize that things
were badly configured, not surprising. Only thing we need to
do it to p

**Comment by belforte** [comment]
I have asked Todor to give you access to the ASO machine where we got the error, that has enough RAM to reproduce the problem.

**Comment by yuyiguo** [comment]
Thanks !

**Comment by belforte** [comment]
for the record, I verified all existing block in input dataset `

**Comment by yuyiguo** [comment]
@belforte 

Tested against cmsweb-testbed and my VM, the request of bulk insertion did not event reach DBS server so there was no record for the call in the server log files. My guess was that the HTTP error 502 was from the front end.  Here was the error in the front end access log:
"[10/Apr/2017:20:15:01 +0200] cmsweb-testbed.cern.ch 188.184.89.130 "POST /dbs/int/global/DBSWriter/bulkblocks HTTP/1.1" 502 [data: 110701812 in 17728 out 232 body 1555031 us ] [auth: TLSv1.2 DHE-RSA-AES256-GCM-SHA384 "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=yuyi/CN=639751/CN=Yuyi Guo/CN=1390704615" "-" ] [ref: "-" "DBSClient/Unknown/" ]
" 
There were sever reasons for that guess: 
1. the error was getting almost immediately after the call was made.
2. the bulk insert takes several steps to insert the entire block. The lumi insertion was the last step. If it failed because of too much lumi, we should see at least the configurations and dataset inserted into the DB, but there was nothing in the DB.
3. If the call passed to the server, the server on my VM should be "killed" when the VM ran off memory as I did running the test.  But there was nothing happened for the server.     

I need to think about how to handle this since this is not real DBS problem.   I am thinking this may related the front end Apache and its configuration. @BrunoCoimbra , Lina any comments?

**Comment by belforte** [comment]
Thanks @yuyiguo 
Indeed it looks like a CMSWEB issue at this point. So maybe the message is simply too big. Hopefully they can find a more telling message in some other log.
I do not care to make this work, only to detect it early enough to be able to print a clear message.

**Comment by ericvaandering** [comment]
We were just discussing this in our meeting. @belforte remember, lumis are now 23s (why my napkin calculation was different than yours). 

Empty lumis in MC tell you something about the filter efficiency, but I suspect the user did not run 2.4M jobs so is creating multiple lumis per job. Maybe that makes sense in some sort of SUSY parameter scan, but otherwise perhaps not.

Not sure what to do about this, though.

**Comment by vkuznet** [comment]
There are few issues here:
- large size of incoming string (json) and limited window on front/back-ends to handle request. If you're uploading N-MB of data (where N is large) there is no way you can fit into front/back-end window for incoming request which is now I think set to 5 min.
- large string will cause large RAM utilization in python when json will try to load it. This is by nature of json parsing in python, a single string should be sucked and memory allocation should be done for nested structure (dicts/lists). This explain comment about python RAM utilization
- lack of streaming support for front/back-end and our clients

To resolve the issue in general we need:
- modify our clients to send data in chunks (streaming support)
- change data structure of incoming request to support streaming, e.g. go away from nested dicts to flat ones
- change DBS APIs to support data streams

None of them are easy steps and will require architectural changes at different level, but if we anticipate large data request in a future we'll face problem again and again at different level. As we discussed on a meeting an intermediate solution may be to educate users, split large data in smaller chunks. But at the end we should think about about proper remedy. To do that I need to see a structure of the request as well as check DBS API logic.

**Comment by belforte** [comment]
I guess someone did a mistake in setting the initial lumi
of each job, when I asked why the input dataset is in this way,
I got no reply.

**Comment by belforte** [comment]
@vkuznet
I think we should define the limit that is acceptable to
current tools, make a check in the CRAB code, and raise an error.
THis situation was clearly something done wrong by the user,
we earlier and faster we can tell them, them better.

Current tools work finely on all our realustic  use cases.
I do not see the need to improve, at least
not for user's sake.

**Comment by yuyiguo** [comment]
@belforte @vkuznet @ericvaandering 

I am checking old DBS issues to see what I need to do with them. This issue was the user had 2.4 M lumi sections in one dataset and caused http error 502 when inserting.  We discussed to add a limit on the maximum  number of  lumis a user generated block/dataset can have. If DBS counts the number of lumis in the bulk insert, it would be time consuming. Can it  be limited  in crab configuration file or some where in the crab?    If so, what is the reasonable number?

**Comment by belforte** [comment]
good point. 
We are going to limit user data to 1K lumis per file
https://github.com/dmwm/CRABClient/pull/4717

But we do not have an overall cap per block, which is what may kill DBS server (if nothing else, but not bing able to send too large a JSON in a CMSWEB transaction).
Shall we set one at e.g. 100k lumis/block in CRAB publication code, just for sanity ?

**Comment by vkuznet** [comment]
I think limitation factor should be determined from DBS usage itself.
In order to know how many lumis/block we can send in a single request
we need to know how many DBS can handle without affecting the cluster/backend
and end-user. If it can handle 1K, we setup limit to 1k, if it can handle
100K we may choose this limit or lower, etc.

I think Yuyi need to provide a benchmark from DBS injection part how fast
DBS can handle 1k, 10k, 100k, etc. and what is impact on DBS server in
each case.

So far it is unclear to me that even using 1k is justifiable.

**Comment by yuyiguo** [comment]
@belforte @vkuznet @ticoann @amaltaro 

I can do some testing to estimate what DBS can handle, but this is a database usage issue so it depends on how busy the db is at the same inserting occurs and also the file size too.  what I would like to know was that a meaningful total lumi sections per block that CMS real data have. Even if it is the MC data, it has to be consistent with the real data.  For example the 2.4 million lumi section that caused the http error 502 is equivalent to 7 years real data, we should not have this kind of block even if DBS can handle it.  
Talked with @ticoann, in WMAgent they limit 500 files per block and each file sizes are range from 1MB to 1 GB. Is this something CRAB could do, @belforte ?

**Comment by belforte** [comment]
I think CRAB has a limit on #files/block. Let me check.
But problem is #lumis in user-produced MC where they do all possible
unreasonable things, we need to set a low limit.
If 1k lumis per file is too much, we can surely set it lower.

**Comment by yuyiguo** [comment]
Done by put up limit in crab.
