### ISSUE TITLE
Files API bug?

### ISSUE THREAD

**Issue by vkuznet** [dmwm/DBS#555]
Yuyi, I'm trying to understand the following DBS issue:

if I look-up the following file
/store/mc/Summer10/Ztautau_M20_CTEQ66-powheg/GEN-SIM-RECO/START36_V9_S09-v1/0026/02579C1B-E276-DF11-949B-00261894380D.root
and ask for detailed output I get the following record

```
scurl "https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files/?detail=True&logical_file_name=%2Fstore%2Fmc%2FSummer10%2FZtautau_M20_CTEQ66-powheg%2FGEN-SIM-RECO%2FSTART36_V9_S09-v1%2F0026%2F02579C1B-E276-DF11-949B-00261894380D.root"

[{"check_sum": "3830952093", "branch_hash_id": null, "adler32": "9db9ecb2", "block_id": 1633458, "event_count": 4497, "file_type": "EDM", "create_by": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ceballos/CN=488892/CN=Guillelmo Gomez Ceballos Retuerto", "logical_file_name": "/store/mc/Summer10/Ztautau_M20_CTEQ66-powheg/GEN-SIM-RECO/START36_V9_S09-v1/0026/02579C1B-E276-DF11-949B-00261894380D.root", "creation_date": 1276432158, "last_modified_by": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=ceballos/CN=488892/CN=Guillelmo Gomez Ceballos Retuerto", "dataset": "/Ztautau_M20_CTEQ66-powheg/Summer10-START36_V9_S09-v1/GEN-SIM-RECO", "block_name": "/Ztautau_M20_CTEQ66-powheg/Summer10-START36_V9_S09-v1/GEN-SIM-RECO#9c477ff0-1151-4435-8d95-86a068691d6f", "file_id": 21330421, "file_size": 1357489422, "last_modification_date": 1277116605, "dataset_id": 569428, "file_type_id": 1, "auto_cross_section": null, "md5": "NOTSET", "is_file_valid": 1}]
```

but then if I use the same API but add validFileOnly=1 parameter I get nothing
```
scurl "https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files/?
detail=True&logical_file_name=%2Fstore%2Fmc%2FSummer10%2FZtautau_M20_CTEQ66-powheg%2FGEN-SIM-RECO%2FSTART36_V9_S09-v1%2F0026%2F02579C1B-E276-DF11-949B-00261894380D.root&validFileOnly=1"
[]
```
(here scurl is just alias to curl with some parameters).

It seems to me this is a bug in files API.
Please confirm.
Best,
Valentin.

**Comment by vkuznet** [comment]
Here is another example:
```
scurl "https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files/?dataset=%2FZeroBias%2FRun2010B-Dec4ReReco_v1%2FRECO&run_num=148126&detail=True&validFileOnly=1"
[]
```

and

```
scurl "https://cmsweb.cern.ch/dbs/prod/global/DBSReader/files/?dataset=%2FZeroBias%2FRun2010B-Dec4ReReco_v1%2FRECO&run_num=148126&detail=True"
[{"run_num": 148126, "check_sum": "3586702645", "branch_hash_id": null, "adler32": "12b6a23a", "block_id": 2481380, "event_count": 2642, "file_type": "EDM", "create_by": "cmsdataops@cmssrv112.fnal.gov", "logical_file_name": "/store/data/Run2010B/ZeroBias/RECO/Dec4ReReco_v1/0213/DC73B1D1-8A01-E011-AA3B-0026189438F2.root", "creation_date": 1291675981, "last_modified_by": "/DC=org/DC=doegrids/OU=Services/CN=uscmspilot-test/cmssrv38.fnal.gov", "dataset": "/ZeroBias/Run2010B-Dec4ReReco_v1/RECO", "block_name": "/ZeroBias/Run2010B-Dec4ReReco_v1/RECO#364e30d0-13b6-449f-9b7d-8dd80d67ceb8", "file_id": 26311588, "file_size": 230454425, "last_modification_date": 1291697630, "dataset_id": 1183511, "file_type_id": 1, "auto_cross_section": null, "md5": "NOTSET", "is_file_valid": 1}]
```

So the problem is related to using validFileOnly=1 parameter in files API query regardless of passed other parameters.

**Comment by yuyiguo** [comment]
Valentin,
This is not a bug, but a feature.
There are two places in DBS to check if a piece of data is valid or not. The first place is the dataset, if a dataset is invalid, then everything is invalid under the dataset. Then at a file level, a dataset may be valid, but a file under it may be invalid. The first case you gave is exact the case that a dataset is invalid, but the file is valid. So when you ask to list the file with detail and it show the info at the file level and give you everything without check if the file is indeed valid or not.  However, The validFileOnly=1 is turned on, DBS has to check everything about the file, then it found the dataset is invalid, so you got [ ]. Below is the call to show what I explained here.

https://cmsweb.cern.ch/dbs/prod/global/DBSReader/datasets?detail=1&dataset_access_type=*&logical_file_name=%2Fstore%2Fmc%2FSummer10%2FZtautau_M20_CTEQ66-powheg%2FGEN-SIM-RECO%2FSTART36_V9_S09-v1%2F0026%2F02579C1B-E276-DF11-949B-00261894380D.root

**Comment by vkuznet** [comment]
Hmm, I don't think I like it, the choice of parameter name is confusing since it
said valid *File* Only instead of validOnly.

And, the description on DBS page
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/
is misleading. It says

param validFileOnly:	default=0 return all the files. when =1, only return files with is_file_valid=1 or dataset_access_type=PRODUCTION or VALID

It said return files with is_file_valid=1, in this case file has this
attribute. Then it applies OR condition for dataset_access_type.

If I follow your logic it should first check the dataset access type and then
is_file_valid.

I would suggest that you provide better description about the usage of this flag
on DBS web page and explicitly lists either the order applied in a code
or clarify the logic itself.

**Comment by ericvaandering** [comment]
The description should be ``` is_file_valid=1 AND dataset_access_type=PRODUCTION or VALID``` it seems.

**Comment by yuyiguo** [comment]
Done
