### ISSUE TITLE
bug in WMCore/DBCore

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#560]
Seangchan's code to find missing parentage has been crashed in recently. Now it is identified that was caused by ORA-0100 error maximum cursor exceeded.  
Bug found here https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBCore.py#L98

CMS databases  have a limit with 600 cursors/session, WMCore code did not close the cursor. While 818 blocks were called for this listBlockParent API and crashed at exactly 599.
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/BlockParent/List.py#L43

We will have to stop use cursor in DBS because wmcore cursor has the bug and it does nothing with the  advantage cursor  anyway. 

We will change DBS code to avoid the bug in WMCore. Replace cursor 
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/BlockParent/List.py#L46
with 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBFormatter.py#L41

**Comment by bbockelm** [comment]
To make sure I understand -- the problem is that the cursors are all buffered inside WMCore before being returned by the function, meaning there's no opportunity to close the in-process results cursors.

Why not change the `processData` API to yield an iterator?  Then, the DBS code could be:

```
        result = []
	for cursor in self.dbi.processData(sql, binds, conn, transaction, returnCursor=True):
            d = self.formatCursor(cursor)
            if d:
                result += d
```

Removes the code duplication and (hopefully) helps others from hitting the same problem.

**Comment by yuyiguo** [comment]
This is a good idea. DBS(listBlockParents) will keep as it is if WMCore (processData) is changed to return a generator. The only thing is that the same API will return a bit different depending on what is the input, but should not be big deal.  The biggest problem with processData function is that it pretends to do a bulk operation, but it actually was doing one by one call to Oracle. The real change would make it a real bulk operation. If not, I would change DBS using generator to change a list of binding to be a single binding with a string of comma separated items.

**Comment by bbockelm** [comment]
Indeed - I was hoping that we could keep `listBlockParents` using `processData`, then actually improve `processData`.  That way, other callers of `processData` would also improve.

@amaltaro - are there other callsites that interact with `processData` which need to be reviewed?

**Comment by amaltaro** [comment]
If the change isn't that hard and everyone would profit of a higher performance, the best would be to actually fix the WMCore issue, which is probably used by several other services (WMAgent, DBS, and I guess CRABServer and TaskWorker - maybe even sitedb?)
