### ISSUE TITLE
Typo in the dbs-client documentation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#586]
Yuyi,
there seems to be a typo on the documentation for listFileSummaries. The key returned is `num_file`, not `num_files` as mentioned in the documentation here:
https://cms-http-group.web.cern.ch/cms-http-group/apidoc/dbs3-client/current/dbs.apis.html#dbs.apis.dbsClient.DbsApi.listFileSummaries

**Comment by yuyiguo** [comment]
Thanks Alan, I will correct it in next release.
Yuyi

**Comment by yuyiguo** [comment]
Sone. in 3.7.8.
