### ISSUE TITLE
validFileOnly=True for listFileArray doing something unexpected

### ISSUE THREAD

**Issue by vlimant** [dmwm/DBS#588]
dbsapi = DbsApi(url=dbs_url)
dataset = '/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_CP5Up/RunIIFall17DRPremix-PU2017_94X_mc2017_realistic_v11-v1/AODSIM'
files = dbsapi.listFileArray( dataset= dataset,validFileOnly=True, detail=True)
print [(f['is_file_valid'],f['logical_file_name']) for f in files]

returns an empty list []

with validFileOnly=False, I get

[(1, '/store/mc/RunIIFall17DRPremix/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_CP5Up/AODSIM/PU2017_94X_mc2017_realistic_v11-v1/90000/76BC5566-0829-E811-9BBC-B4969109FA2C.root'), (1, '/store/mc/RunIIFall17DRPremix/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_CP5Up/AODSIM/PU2017_94X_mc2017_realistic_v11-v1/90000/62D8450E-9128-E811-98B2-E0071B7B2350.root'), (1, '/store/mc/RunIIFall17DRPremix/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_CP5Up/AODSIM/PU2017_94X_mc2017_realistic_v11-v1/30000/FC6C9EF8-7E73-E811-B47D-0090FAA57730.root'), (1, '/store/mc/RunIIFall17DRPremix/ttHJetToGG_M125_13TeV_amcatnloFXFX_madspin_pythia8_CP5Up/AODSIM/PU2017_94X_mc2017_realistic_v11-v1/30000/5EFC3EC1-7E73-E811-ABDA-44A84225C851.root')]

is there something I am missing ?

**Comment by yuyiguo** [comment]
Yes. 
validFileOnly means that the dataset has to be valid too. When a dataset is invalid, it does not matter that if the is_files_valid  of the files is 1 or 0, everything under it is in valid.

**Comment by yuyiguo** [comment]
If one invalidates the dataset and choose recursively it should invalidate files too, of course the person has to use the script DBS provided in order to do it correctly.

**Comment by vlimant** [comment]
I am assuming https://github.com/dmwm/DBS/blob/master/Client/utils/DataOpsScripts/DBS3SetDatasetStatus.py or is there something directly in the restapi/client that can do the natural dataset=invalid => files=invalid ?

**Comment by yuyiguo** [comment]
Yes, it is.
