### ISSUE TITLE
Change the DBS versioning format

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#592]
As already discussed in the previous months and also pointed out by Erik's PR:
https://github.com/dmwm/DBS/pull/591

we need to change the format of the DBS version such that we can start packaging and uploading DBS-* services to Pypi.

My suggestion would be to use the same'ish format used in WMCore/CMSSW, e.g.:
1.2.3.pre2 (pre-release)
1.2.3.patch5 (patch release)
1.2.3 (final release)
1.2.3.cmsweb1 (hot fix release for cmsweb)

You can also find some documentation on this service tagging here:
https://github.com/dmwm/WMCore/wiki/TaggingAndReleasing

@yuyiguo can you please try to make this change for the next week such that we can move forward with the Pypi development work? Thanks

**Comment by yuyiguo** [comment]
DBS version has schema DBS_M_N_P currently, such as DBS_3_7_7. The new schema will be 3.7.7.

**Comment by ericvaandering** [comment]
Are these just GH tags?

**Comment by yuyiguo** [comment]
yes

**Comment by yuyiguo** [comment]
@amaltaro @goughes 
The current DBS version is 3.7.8.
