### ISSUE TITLE
Make DBS client distribution 

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#619]
Crab client is going to use dasgoclient.  So they think they don't need to use DBS client any more, therefore, they are going to remove DBS client from Crab client distribution.  See https://github.com/dmwm/CRABClient/issues/4870

We will need to distribute DBS client independently.

**Comment by belforte** [comment]
wel..it is not obvious that this is neede since we can keep indicating dbs client as CRBA Client dependency and thus having it on CVMFS, even if CrabClient code does not use it.

**Comment by yuyiguo** [comment]
Still stays with Crab Client.
