### ISSUE TITLE
Errors from "DBS configuration for NATS integration #821"

### ISSUE THREAD

**Issue by yuyiguo** [dmwm/DBS#620]
@vkuznet 

Please fix the error below and go over the NATS code to fix all similar code.
Thanks,
Yuyi

test07a: web.DBSWriterModel.insertFiles: basic test ... REQUEST [21/Jan/2020 23:00:28] 127.0.0.1 1111 POST / [] [{}]
Tue Jan 21 22:00:28 2020 dbsException-server-error: DBSWriterModel/insertFile. unsupported operand type(s) for +=: 'int' and 'str'
. Exception trace: 
 Traceback (most recent call last):
  File "/data/srv/HG2002c/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.11.0/lib/python2.7/site-packages/dbs/web/DBSWriterModel.py", line 428, in insertFile
    tot_evts += f.get('event_count', 0)
TypeError: unsupported operand type(s) for +=: 'int' and 'str'

**Comment by vkuznet** [comment]
Fixed with commit: 607532e5..a07768fb

**Comment by vkuznet** [comment]
I was not aware that event_count and file_size may be stored as string data types. The changes I placed in a code check for data types and their validity in this context.

**Comment by vkuznet** [comment]
the PR is this: https://github.com/dmwm/DBS/pull/621

**Comment by vkuznet** [comment]
Yuyi,
I checked the code and there is NO more places where casting should be done.
The evt/size are the only attributes which required the cast.

**Comment by yuyiguo** [comment]
Thanks, I will rebuild with a new tag.
Yuyi

**Comment by yuyiguo** [comment]
@vkuznet ,

Please get it correctly. 

File "/data/srv/HG2002c/sw.yuyi/slc7_amd64_gcc630/cms/dbs3/3.11.1/lib/python2.7/site-packages/dbs/web/DBSWriterModel.py", line 429
    if ecount && ecount != None and str(ecount) != "None":
               ^

**Comment by vkuznet** [comment]
Yuyi, sorry multiple languages/tasks.
The fix is here: https://github.com/dmwm/DBS/pull/622
