### ISSUE TITLE
Failed to migrate dataset from prod to int instance

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#631]
Yuyi,

I was investigating why one of our WMCore testing templates was failing to go through, and I just noticed that the dataset from the production DBS instance has not been migrated to the int instance yet. Here is how I just checked:
```
>>> from dbs.apis.dbsClient import DbsApi
>>> dbsApi = DbsApi(url = 'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSMigrate/')
>>> dbsUrl = 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader'
>>> dataset = '/RelValZEE_14/CMSSW_11_1_0_pre4-110X_mcRun3_2021_realistic_v8-v1/GEN-SIM'
>>> 
>>> migrateArgs = {'migration_url': dbsUrl, 'migration_input': dataset}
>>> dbsApi.submitMigration(migrateArgs)
{'migration_details': {'migration_status': 9, 'create_by': 'amaltaro', 'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader', 'last_modified_by': 'amaltaro', 'creation_date': 1585835516, 'retry_count': 3, 'migration_input': '/RelValZEE_14/CMSSW_11_1_0_pre4-110X_mcRun3_2021_realistic_v8-v1/GEN-SIM', 'migration_request_id': 210003, 'last_modification_date': 1585835945}, 'migration_report': 'REQUEST ALREADY QUEUED. Migration terminally failed. '}
>>> 
```

Could you please investigate what the issue is? 

Can you please check whether any migration has actually worked since HG2002? I'm concerned with the removal of `c-ares` in this PR: https://github.com/cms-sw/cmsdist/pull/5438

FYI: @todor-ivanov

**Comment by todor-ivanov** [comment]
Thanks for tagging me here @amaltaro

**Comment by yuyiguo** [comment]
Let me check. 
Crab had problem with migration from prod to phys03 because a new data tier introduced in prod, but not  in phys03 yet.

**Comment by yuyiguo** [comment]
The migration is done. Please check, Alan.
Let me know if any problems. Otherwise, Please close this tickent.

**Comment by amaltaro** [comment]
Thanks, Yuyi. Dataset is now available in testbed:
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/filesummaries?dataset=/RelValZEE_14/CMSSW_11_1_0_pre4-110X_mcRun3_2021_realistic_v8-v1/GEN-SIM

Closing the ticket!
